image: docker

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:

  - deploy

pages:
  stage: deploy
  before_script:
  - docker info
  script:
  - apk add docker-compose
  - docker-compose run --rm foliant make site --with slate
  - mv *.slate public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  only:
      - main
